INSERT INTO features (id, name, description, dataset_id, is_default, is_list, color, properties)
VALUES
    ('action_verbs', 'Verbs', 'Action verbs such as traduit (translated), commenté (commented), augmenté (expanded) that describe the role the contemporary scholar played in bringing about the work.', 'tps', 1, 1, '#954caf', '[]'),
    ('audience', 'Intended Audience', 'Explicit mentions of the work''s intended recipients or audience.', 'tps', 1, 1, '#E4A0D8', '[]'),
    ('base_content', 'Base Content', 'The minimal designation of the book’s main content, typically appearing at the beginning of the title page, without elaboration.', 'tps', 1, 0, '#FADADD', '[]'),
    ('bound_with', 'Bound With', 'Mentions of other works included in the book, such as ''Optics''.', 'tps', 1, 1, '#FFB6C1', '[]'),
    ('content_description', 'Base Content Description', 'Additional elements extending beyond the base content, describing it or highlighting the book’s special features.', 'tps', 0, 0, '#AEC6CF', '[]'),
    ('date_in_imprint', 'Date in Imprint', 'The date of publication as it appears on the title page, typically in the form of a year.', 'tps', 0, 0, '#FFDEAD', '[]'),
    ('dedicatee_name', 'Patronage Dedication', 'Mentions of patrons.', 'tps', 1, 0, '#D4C5F9', '[]'),
    ('dedication_in_imprint', 'Dedication in Imprint', 'Mentions of dedications to patrons or other individuals, typically found on the title page or in the preface.', 'tps', 0, 1, '#D4C5F9', '[]'),
    ('description_of_euclid', 'Euclid Description', 'Any descriptors found alongside the Euclid''s name, such as mentioning him being a mathematician.', 'tps', 1, 1, '#b0e57c', '[]'),
    ('destination_language', 'Destination Language', 'Mentions of the target language of the edition or translation (e.g., “en François”, “in English”).', 'tps', 1, 1, '#e59c67', '["language"]'),
    ('edition_details', 'Edition Statement', 'Any information that is highlighted as relevant for this specific edition.', 'tps', 1, 0, '#FFC1CC', '[]'),
    ('editor_description', 'Adapter Description', 'Any descriptors found alongside the adapter name, such as academic titles, ranks, or affiliations.', 'tps', 1, 0, '#FFDAB9', '[]'),
    ('editor_description_in_imprint', 'Adapter Description in Imprint', 'Any descriptors found alongside the author name, such as academic titles, ranks, or affiliations.', 'tps', 0, 1, '#FFDAB9', '[]'),
    ('editor_in_imprint', 'Adapter Attribution in Imprint', 'The name of the author as it appears on the title page, typically in the form of ''by [Author Name]''.', 'tps', 0, 0, '#909fd7', '[]'),
    ('editor_name', 'Adapter Attribution', 'The name of the contemporary adapter (author, editor, translator, commentator, etc.) as it appears on the title page.', 'tps', 1, 0, '#909fd7', '[]'),
    ('educational_authorities_references', 'Other Educational Authorities', 'Mentions of other scholars, either ancients, such as Theon of Alexandria, or contemporary, like Simon Stevin.', 'tps', 1, 1, '#e567ac', '["ancient_persona"]'),
    ('elements_designation', 'Elements Designation', 'The designation of the Elements, such as ''Elements of Geometry'' or ''Euclid’s Elements'', as it appears on the title page.', 'tps', 0, 0, '#A3D5C3', '[]'),
    ('enriched_with', 'Enriched With', 'Mentions of additional content that is not part of the core text that enriches the text and makes it more understandable, accurate, or useful.', 'tps', 1, 1, '#D3D3D3', '[]'),
    ('greek_text', 'Greek designation', 'Greek designation of the book in non-Greek books.', 'tps', 0, 0, '#F0B2A1', '[]'),
    ('institutions', 'Institutions', 'Mentions of institutions, such as societies or universities, associated with the book.', 'tps', 1, 1, '#B0C4DE', '["institution"]'),
    ('location_in_imprint', 'Place in Imprint', 'The place of publication as it appears on the title page, typically a city.', 'tps', 0, 1, '#E6E6FA', '[]'),
    ('origin_language', 'Explicit Language References', 'Mentions of the source language (e.g., Latin or Greek) and/or the target language.', 'tps', 1, 1, '#e59c67', '["language"]'),
    ('printing_privilege', 'Publishing Privileges', 'Mentions of royal privileges or legal permissions granted for printing.', 'tps', 1, 0, '#D1E7E0', '[]'),
    ('printing_privilege_in_imprint', 'Privileges in Imprint', 'Mentions of royal privileges or legal permissions granted for printing, such as ''by royal permission'' or ''with the approval of the censor''.', 'tps', 0, 1, '#D1E7E0', '[]'),
    ('publisher_in_imprint', 'Publisher in Imprint', 'The name of the publisher or printer as it appears on the title page.', 'tps', 0, 1, '#ADD8E6', '[]'),
    ('references_to_euclid', 'Euclid References', 'Euclid''s name as it appears on the title page.', 'tps', 1, 1, '#F0E68C', '[]')
ON CONFLICT(id) DO NOTHING;

INSERT INTO feature_revisions (id, name, description, dataset_id, feature_id, prompt, categorizer)
VALUES
    ('d2629d84-c4ab-44ee-905e-1a930448ad28', 'v1', 'Initial seeded revision', 'tps', 'action_verbs', 'Action verbs such as traduit (translated), commenté (commented), augmenté (expanded) that describe the role the contemporary scholar played in bringing about the work.', 'csv_import'),
    ('a0da0c3f-bd0b-4a21-b105-4fd8f50b3307', 'v1', 'Initial seeded revision', 'tps', 'audience', 'Explicit mentions of the work''s intended recipients or audience.', 'csv_import'),
    ('607cf109-416b-4e0d-897f-06509a1dc6f9', 'v1', 'Initial seeded revision', 'tps', 'base_content', 'The minimal designation of the book''s main content, typically appearing at the beginning of the title page, without elaboration.', 'csv_import'),
    ('edba08e1-a1c0-461a-b214-0949d808dd64', 'v1', 'Initial seeded revision', 'tps', 'bound_with', 'Mentions of other works that are included in the work, in addition to Euclid''s Elements, such as ''Optics'', ''Data'', theorems by Archimedes. Mentions of additions ingrained in the core text and written by the adapter/translator of the text, such as examples or explanations, should not be included here. Try to mark the minimal unit of the bound work and break down the bound works into their components when possible.', 'csv_import'),
    ('2efc30cf-b777-410c-a720-5c78c5ba6e5e', 'v1', 'Initial seeded revision', 'tps', 'content_description', 'Additional elements extending beyond the base content, describing it or highlighting the book’s special features.', 'csv_import'),
    ('8e50c14b-39a7-4579-93b7-ca907ec54e15', 'v1', 'Initial seeded revision', 'tps', 'date_in_imprint', 'Mentions of the date, usually in the form of a year, when the book was printed or published.', 'csv_import'),
    ('5ce30c62-1623-41c4-99be-802433e60569', 'v1', 'Initial seeded revision', 'tps', 'dedicatee_name', 'Mentions of patrons or dedication.', 'csv_import'),
    ('a2f6fa30-532e-4064-85ba-da1b424f8cc4', 'v1', 'Initial seeded revision', 'tps', 'dedication_in_imprint', 'Mentions of patrons or dedications.', 'csv_import'),
    ('035d02db-b06b-4086-a0e2-7a8fbe8d393a', 'v1', 'Initial seeded revision', 'tps', 'description_of_euclid', 'Any descriptors found alongside Euclid''s name, such as mentioning him being a mathematician.', 'csv_import'),
    ('5a3a9abb-9657-48a1-84fe-ff3fff1e084a', 'v1', 'Initial seeded revision', 'tps', 'destination_language', 'Mentions of the target language of the edition or translation (e.g., “en François”, “in English”).', 'csv_import'),
    ('806d147e-8bc0-46ea-8875-f31b8b1383b4', 'v1', 'Initial seeded revision', 'tps', 'edition_details', 'Any information that is highlighted as relevant for this specific edition such as claims regarding the corrections and revisions introduced in it.', 'csv_import'),
    ('ed9226e3-7a8d-4e94-bc39-dd73bebc1200', 'v1', 'Initial seeded revision', 'tps', 'editor_description', 'Any descriptors found alongside the adapter name, such as academic titles, ranks, or affiliations.', 'csv_import'),
    ('37dbf197-45ac-469e-b9b1-a6b8216f42b7', 'v1', 'Initial seeded revision', 'tps', 'editor_description_in_imprint', 'Any descriptors found alongside the adapter name, such as academic titles, ranks, or affiliations. Do not include printer or publisher.', 'csv_import'),
    ('90cc0374-ec89-4b87-8d14-62952901ca69', 'v1', 'Initial seeded revision', 'tps', 'editor_in_imprint', 'The name of the contemporary adapter (author, editor, translator, commentator, etc.) as it appears on the title page. Do not include descriptors and do not include printer or publisher.', 'csv_import'),
    ('8a783262-4a60-4566-addd-2723c7eabd5c', 'v1', 'Initial seeded revision', 'tps', 'editor_name', 'The name of the contemporary adapter (author, editor, translator, commentator, etc.) as it appears on the title page.', 'csv_import'),
    ('7aa930a4-fee6-4e56-a2b1-ee33d86cdada', 'v1', 'Initial seeded revision', 'tps', 'educational_authorities_references', 'Mentions of other scholars, either ancients, such as Theon of Alexandria, or contemporary, like Simon Stevin.', 'csv_import'),
    ('99423161-7ccd-4c7b-9f99-b9d919aae77d', 'v1', 'Initial seeded revision', 'tps', 'elements_designation', 'The designation of the Elements, such as ''Elements of Geometry'' or ''Euclid’s Elements'', as it appears on the title page.', 'csv_import'),
    ('34ce5e13-4831-415f-b0a2-dc353bcdac23', 'v1', 'Initial seeded revision', 'tps', 'enriched_with', 'Mentions of additional content that is not part of the core text, such as illustrations, diagrams, explanations, expositions, examples or other supplementary material that enriches the text. Try to mark the minimal unit of enrichment and break down the enrichment into components when possible.', 'csv_import'),
    ('6bdcf7b6-3f87-4f03-9928-1705ba8c7e04', 'v1', 'Initial seeded revision', 'tps', 'greek_text', 'Greek designation of the book in non-Greek books.', 'csv_import'),
    ('34ae1344-67cb-47b8-b194-6773c85b6016', 'v1', 'Initial seeded revision', 'tps', 'institutions', 'Mentions of institutions, such as societies or universities, associated with the book.', 'csv_import'),
    ('0174492c-bdd7-4e7a-9c85-48b3af204e70', 'v1', 'Initial seeded revision', 'tps', 'location_in_imprint', 'Mentions of the city or town where the book was printed or published. Do not include full addresses, just the city or town name.', 'csv_import'),
    ('1d071f54-3b58-4c7e-8a48-e1a8b5730881', 'v1', 'Initial seeded revision', 'tps', 'origin_language', 'Mentions of the source language (e.g., Latin or Greek) and/or the target language.', 'csv_import'),
    ('fc467a41-a7ed-4288-aa50-0e1c9aa36793', 'v1', 'Initial seeded revision', 'tps', 'printing_privilege', 'Mentions of royal privileges or legal permissions granted for printing.', 'csv_import'),
    ('68122d95-b49d-4776-bb5d-12943b7c31da', 'v1', 'Initial seeded revision', 'tps', 'printing_privilege_in_imprint', 'Mentions of royal privileges or legal permissions granted for printing.', 'csv_import'),
    ('de12d28f-39bb-4cc2-8531-4edd234068a2', 'v1', 'Initial seeded revision', 'tps', 'publisher_in_imprint', 'Mentions of the publisher or printer. Try to include the minimal unit of the publisher''s name.', 'csv_import'),
    ('9892c728-9af0-451a-849e-ccfce6a5007f', 'v1', 'Initial seeded revision', 'tps', 'references_to_euclid', 'Euclid''s name as it appears on the title page.', 'csv_import')
ON CONFLICT(id) DO NOTHING;
