yarnPath: .yarn/releases/yarn-4.12.0.cjs
packageExtensions:
  "@react-pdf-viewer/attachment@*":
    dependencies:
      pdfjs-dist: "3.4.120"
  "@react-pdf-viewer/bookmark@*":
    dependencies:
      pdfjs-dist: "3.4.120"
  "@react-pdf-viewer/core@*":
    dependencies:
      pdfjs-dist: "3.4.120"
  "@react-pdf-viewer/default-layout@*":
    dependencies:
      pdfjs-dist: "3.4.120"
  "@react-pdf-viewer/full-screen@*":
    dependencies:
      pdfjs-dist: "3.4.120"
  "@react-pdf-viewer/get-file@*":
    dependencies:
      pdfjs-dist: "3.4.120"
  "@react-pdf-viewer/open@*":
    dependencies:
      pdfjs-dist: "3.4.120"
  "@react-pdf-viewer/page-navigation@*":
    dependencies:
      pdfjs-dist: "3.4.120"
  "@react-pdf-viewer/print@*":
    dependencies:
      pdfjs-dist: "3.4.120"
  "@react-pdf-viewer/properties@*":
    dependencies:
      pdfjs-dist: "3.4.120"
  "@react-pdf-viewer/rotate@*":
    dependencies:
      pdfjs-dist: "3.4.120"
  "@react-pdf-viewer/scroll-mode@*":
    dependencies:
      pdfjs-dist: "3.4.120"
  "@react-pdf-viewer/search@*":
    dependencies:
      pdfjs-dist: "3.4.120"
  "@react-pdf-viewer/selection-mode@*":
    dependencies:
      pdfjs-dist: "3.4.120"
  "@react-pdf-viewer/theme@*":
    dependencies:
      pdfjs-dist: "3.4.120"
  "@react-pdf-viewer/thumbnail@*":
    dependencies:
      pdfjs-dist: "3.4.120"
  "@react-pdf-viewer/toolbar@*":
    dependencies:
      pdfjs-dist: "3.4.120"
  "@react-pdf-viewer/zoom@*":
    dependencies:
      pdfjs-dist: "3.4.120"
