[build]
  publish = "elements-resource-box/dist"
  environment = { VITE_BASE_PATH = "/", VITE_BACKEND_URL="https://euclides.huma-num.fr/commentaria", VITE_RESOURCEBOX_APP_URL="https://euclides.huma-num.fr/resourcebox", VITE_COMMENTARIA_APP_URL="https://euclides.huma-num.fr/hub" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
