// Command gendialect compiles the shared Markdown dialect document into the
// transcriptioncorrector package. The generated value lets deployed binaries
// use the repository-level document without depending on the source tree at
// runtime.
package main

import (
	"flag"
	"fmt"
	"go/format"
	"os"
	"strconv"
)

func main() {
	input := flag.String("input", "", "path to the canonical Markdown dialect document")
	output := flag.String("output", "", "path for the generated Go source")
	flag.Parse()

	if *input == "" || *output == "" {
		fmt.Fprintln(os.Stderr, "both -input and -output are required")
		os.Exit(2)
	}

	contents, err := os.ReadFile(*input)
	if err != nil {
		fmt.Fprintf(os.Stderr, "read dialect document: %v\n", err)
		os.Exit(1)
	}

	source := []byte("// Code generated by gendialect; DO NOT EDIT.\n\n" +
		"package transcriptioncorrector\n\n" +
		"const markdownDialect = " + strconv.Quote(string(contents)) + "\n")
	source, err = format.Source(source)
	if err != nil {
		fmt.Fprintf(os.Stderr, "format generated source: %v\n", err)
		os.Exit(1)
	}
	if err := os.WriteFile(*output, source, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "write generated source: %v\n", err)
		os.Exit(1)
	}
}
