// Command gendialect compiles the shared Markdown dialect document into the
// transcriptioncorrector package. The generated value lets deployed binaries
// use the repository-level document without depending on the source tree at
// runtime.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"strconv"
)

const (
	contractBeginMarker = "<!-- BEGIN LLM CONTRACT -->"
	contractEndMarker   = "<!-- END LLM CONTRACT -->"
)

func main() {
	input := flag.String("input", "", "path to the canonical Markdown dialect document")
	output := flag.String("output", "", "path for the generated Go source")
	flag.Parse()

	if *input == "" || *output == "" {
		fmt.Fprintln(os.Stderr, "both -input and -output are required")
		os.Exit(2)
	}

	contents, err := os.ReadFile(*input)
	if err != nil {
		fmt.Fprintf(os.Stderr, "read dialect document: %v\n", err)
		os.Exit(1)
	}
	contract, err := extractLLMContract(contents)
	if err != nil {
		fmt.Fprintf(os.Stderr, "extract LLM contract: %v\n", err)
		os.Exit(1)
	}

	source := []byte("// Code generated by gendialect; DO NOT EDIT.\n\n" +
		"package transcriptioncorrector\n\n" +
		"const markdownDialect = " + strconv.Quote(string(contract)) + "\n")
	source, err = format.Source(source)
	if err != nil {
		fmt.Fprintf(os.Stderr, "format generated source: %v\n", err)
		os.Exit(1)
	}
	if err := os.WriteFile(*output, source, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "write generated source: %v\n", err)
		os.Exit(1)
	}
}

func extractLLMContract(document []byte) ([]byte, error) {
	begin := []byte(contractBeginMarker)
	end := []byte(contractEndMarker)
	if bytes.Count(document, begin) != 1 || bytes.Count(document, end) != 1 {
		return nil, fmt.Errorf("document must contain exactly one %q and one %q marker", contractBeginMarker, contractEndMarker)
	}
	start := bytes.Index(document, begin) + len(begin)
	finish := bytes.Index(document, end)
	if finish <= start {
		return nil, fmt.Errorf("end marker must follow begin marker")
	}
	contract := bytes.TrimSpace(document[start:finish])
	if len(contract) == 0 {
		return nil, fmt.Errorf("contract between markers is empty")
	}
	return append(append([]byte(nil), contract...), '\n'), nil
}
